name: CICD Cypress

on:
  push:
    branches:
      - main

jobs:
  run-cypress-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --dev

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('yarn.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-
      - name: Give Cypress executable permissions
        run: chmod +x node_modules/.bin/cypress


      - name: Install Cypress binary
        run: npx cypress install  # Ensure the Cypress binary is downloaded

      - name: Run Cypress Tests
        run: npx cypress run
